# Generated by Django 6.0.3 on 2026-04-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='+66 2 000 1234', help_text='Phone number displayed in the top bar and contact page. Include country code, e.g. +66 2 000 1234', max_length=30)),
                ('phone_dialable', models.CharField(default='+6620001234', help_text='Phone number used for the tel: link (digits only, no spaces), e.g. +6620001234', max_length=30)),
                ('email', models.EmailField(default='info@gfi.co.th', help_text='Contact email displayed in the top bar and contact page.', max_length=254)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
